version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CRYPTOCOMPARE_API_KEY=${CRYPTOCOMPARE_API_KEY}
      - APP_ENV=${APP_ENV}
      - SNAPSHOT_ENABLED=${SNAPSHOT_ENABLED}
